# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u6587\u7ae0\u7b80\u4ecb')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5168\u6587')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('content', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=32, verbose_name='\u6743\u9650\u540d')),
                ('read_own_article', models.SmallIntegerField(verbose_name='\u9605\u8bfb\u81ea\u5df1\u7684\u6587\u7ae0')),
                ('alter_own_article', models.SmallIntegerField(verbose_name='\u4fee\u6539\u81ea\u5df1\u7684\u6587\u7ae0')),
                ('delete_own_article', models.SmallIntegerField(verbose_name='\u5220\u9664\u81ea\u5df1\u7684\u6587\u7ae0')),
                ('crate_article', models.SmallIntegerField(verbose_name='\u7f16\u5199\u6587\u7ae0')),
                ('read_all_article', models.SmallIntegerField(verbose_name='\u9605\u8bfb\u5168\u90e8\u6587\u7ae0')),
                ('alter_all_article', models.SmallIntegerField(verbose_name='\u4fee\u6539\u5168\u90e8\u6587\u7ae0')),
                ('delete_all_article', models.SmallIntegerField(verbose_name='\u5220\u9664\u5168\u90e8\u6587\u7ae0')),
                ('create_comment', models.SmallIntegerField(verbose_name='\u521b\u5efa\u8bc4\u8bba')),
                ('delete_own_comment', models.SmallIntegerField(verbose_name='\u5220\u9664\u81ea\u5df1\u7f16\u5199\u7684\u8bc4\u8bba')),
                ('delete_other_article', models.SmallIntegerField(verbose_name='\u5220\u9664\u81ea\u5df1\u6587\u7ae0\u4e0b\u7684\u8bc4\u8bba')),
                ('delete_all_comment', models.SmallIntegerField(verbose_name='\u5220\u9664\u5168\u90e8\u8bc4\u8bba')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=32, verbose_name='\u89d2\u8272\u540d')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('nick_name', models.CharField(max_length=64)),
                ('gender', models.CharField(blank=True, choices=[('\u5973', 0), ('\u7537', 1)], max_length=5, null=True)),
                ('avatar', models.CharField(default='/static/img/avatar/user_default_avatar1.jpg', max_length=64)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Role')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='article',
            name='whole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleContent'),
        ),
    ]
