# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('title', models.CharField(max_length=32, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('content', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('nick_name', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('\u5973', 0), ('\u7537', 1)], max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
    ]
