# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180920_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(max_length=64),
        ),
    ]
