# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180920_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(default='/static/img/avatar/user_default_avatar1'),
        ),
    ]
